language: node_js
node_js: stable
sudo: required
addons:
  # firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - npm run test
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
    - secure: >-
        iRkogIB6U8waHKWgx0JODqYqiruULtqf3lHi8yhDcV5gU3zthNhKANJVYOq9ZLQRrDPaPPg1dXQc3XObnTiUI82TOjXRzE38tN1PyNiRre9QpZKarirLfa0dl3Wd7iHUJJ2uBVw2RdZ7wbjPjh3iNrQu52PplFGhgze0ra72nxb0HHLsY7JFrINytBmgFGJ4EC4v4UEFvTXywdDhaGmpbO4y4BVnUVaVPfEYnLy8b+GHNPmq3yJU0lphtYiZ1JOw4FLOxmilB8fjgx2pjwO3NR6DfQIxKYk3prkR1iNqjYJdhCCaKi+Vwvd4+zcVSYaZhlCvVICgMsaiSwWWA1F6RKeWtTZvpxpZDpbG5uWiDyfFwQeoNkPlXliUv8edhSK1mON3PW2e93PDOFSfV5S5LhJwsC4WORXiIQR0l+tEn6e9AYDKk0Lg8dwGgaHxK16C552JrKwMrvEL3aArpS0AaRXH2h6DLvhTs3l4p3znKWDabR6E56n8rJ9W2RJtEQ9rMtiZjyJcS1/1BHG1fV6lU5ZWxvBI3vSbuQT+FnkDBq6OTU2W7T7WFN6Bcp4P/TgxiC2BGYVKWvYnteoXEEgLCJ+eBzNqG2ipGBes8ht8FbpyFbZR7B3M7jXi1rpZvwWooFVdlbJLEgLqHCOrQwzAFn34FjyUiSviNE8hc5QcJyw=
    - secure: >-
        c+yEeItGCgLr2ycYdrmCcF8MF6pyecP4d3mN/I1mc5SXEuYjFKuLECAZ2pt9E86rgIFzQpRkFvSvoaz8gtdOugrCkL2IgkKalV0kA+qzqI6Hbv0h0OXgLwqN6EJv+afy1HPmiS99OFi3BQ9qV0pHLn4NVaTGq66AF4A7VPlJnoMnKl7Y2d+d1i+aegfWMwHgCj20Lk8K0aAI9UBF43p9E5YH7pU0yLwhSCOhwcZLW3B+ZOzi5CxvQkE4iOTdWE57beM1GDwm/NueSirP7hLZhP2gSxKyRK3TlaHrmketM0ygsE8HtGF05KrDeyX4FrjZ/1k2JcMlpNgfYBoprOK/GRTB8k9Cn09GpNu0YvMkllewShD9UahuAKT9g1l/VGpSHCCRzN2ZkJPpWzZfo+JicJEP5lpmlZoYyUOYQgDQ8i4Y73AjhN+KqIfNFFK3jWAB3lxZLAJwdASf/WdqmXXWBpjy9WYQ/EVECi7+l6Nctnb4bS2Hpq4BM0MpDFUuAE5sGmXszHLbNg+L/Xo9sO4ccuRzkdxcVouq6EGeqBtU0VVhA9pGzHH8viA4VNy7PgzcGMa1r0gn2XGOJnekAqPQU9+HKAwRb7VIpDAEB6ol8OkJap5ro5TVv/dFdGvjyqD+QtrBqk4aGN3ibXQQ/3XRy0PrhJc6VEUqFgSZq1l+zn0=
